version: "3"
services:
  dogovorapi:
    build: .
    ports:
      - "7254:7254"
      - "5254:5254"
    container_name: "dogovorteam.api"
    networks:
      - dogovor-network
networks:
  dogovor-network:
    driver: bridge
